### ISSUE TITLE
What is the purpose of this library!? 

### ISSUE THREAD

**Issue by DavidSouther** [backbone-boilerplate/grunt-bbb-server#5]
Why does it exist!? What does it do!? How do I configure this!? 

```
*options.separator*

Type: String Default value: ', '

A string value that is used to do something with whatever.
```

The hell does that mean?!!?!?!??!?!?

**Comment by landau** [comment]
:+1:

**Comment by tbranyen** [comment]
@DavidSouther Are you volunteering your available free time to help document the project? I'd be happy to walk you through the source over Skype or Google Hangouts, whatever works best for you.  You have an enthusiasm and desire I cannot hope to match and am super excited to have you on board!

**Comment by DavidSouther** [comment]
Nah, I'll stick with grunt-contrib-connect. I have zero desire to duplicate excellent functionality. Thanks for your encouragement!
