### ISSUE TITLE
express deprecated res.sendfile: Use res.sendFile instead

### ISSUE THREAD

**Issue by feryardiant** [backbone-boilerplate/grunt-bbb-server#6]
Hi! I'm new here and just try to install @backbone-boilerplate/backbone-boilerplate which is depend on this plugin. Everything seems fine, until I run `grunt default server:release` and open `localhost:8000` on my web browser. I just got an empty page with this deprecation log in my terminal.

``` bash
$ grunt default server:release
...
Running "server:release" (server) task
Listening on http://0.0.0.0:8000
express deprecated res.sendfile: Use res.sendFile instead node_modules/grunt-bbb-server/tasks/server.js:334:15
```

![bbb-server](https://cloud.githubusercontent.com/assets/508665/4502000/7c1e9462-4abb-11e4-8f55-1a5c21fab8f1.png)

Is it bug?

**Comment by tbranyen** [comment]
This was just patched, I'll push out a new release soon.  Thanks for the heads up!
